name: Python-CI

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8]
        exclude:
          - os: macos-latest
            python-version: 3.7

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        shell: bash
        run: python -c "import sys; print(sys.version)"
